### ISSUE TITLE
Copyright violation in modified library

### ISSUE THREAD

**Issue by gcacace** [DWorkS/ASignature#1]
Hi, I noticed you literally copied my library (https://github.com/gcacace/android-signaturepad), removing my name from the Copyright.
Accordingly to the APACHE 2.0 License, you MUST put my Copyright on your modified library.

**Comment by 1hakr** [comment]
Hey @gcacace i didn't copy it from your library. If i had know that your library exists, i wouldn't have created this library itself. This library's source is from https://corner.squareup.com/2012/07/smoother-signatures.html and some stackoverflow post i came across which i dont remember. You can check my other libraries where is give full credits to the original developer, if i reuse his code. I saw your code and it shares similar patterns, but i definitely didn't copy your code. I'm okay giving credits, if its reaaly your code. If you can prove its your code that i modified, I will be more than happy to give credit because i love open source.
